apiVersion: v1
appVersion: 0.0.25
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: zeebe-cloud-events-router
version: 0.0.25
