apiVersion: v1
appVersion: 0.0.51
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: zeebe-cloud-events-router
version: 0.0.51
